sonar.projectKey=adamoutler_dash
sonar.organization=adamoutler
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src,cli
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,src/static/**
